### ISSUE TITLE
Email Verification

### ISSUE THREAD

**Issue by UnCimex** [Pr0t0ns/Discord-Joiner#2]
Hey,

The bot is working fine :) However, you can not do anything with the tokens, because you need an email verification directly... Would be great if you could add that

**Comment by Pr0t0ns** [comment]
Hi, Thank you for the suggestion but unfourtanetly discord has extremely advanced bot detection/prevention features. So even if I add Email Verification the tokens will still be flagged/locked/disabled this repo was made for offline member boosting since that's the only thing that they don't monitor as of now.
